version: '3.8'

services:
  openai-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openai-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./config:/root/config
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s